# Consulta que devuelve las URIs y etiquetas de los elementos del nivel 2 hijos de A.
PREFIX  xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
SELECT DISTINCT ?x  ?y
WHERE {
 ?x rdf:type skos:Concept.
 ?x skos:inScheme <http://stats.linkeddata.es/voc/clasificaciones/cnae/AYUDACOD_CNAE> .
 ?x rdfs:label ?y .
 ?x skos:broader <http://stats.linkeddata.es/voc/clasificaciones/cnae/CNAE93/A> .
 ?x xkos:depth "2"
}